export const SETTINGS_OPTIONS = [
  { title: "Minha conta", isHeader: true, key: Math.random().toString() },
  {
    title: "Meu PicPay",
    subtitle: "@leonardo.nascimento951",
    key: Math.random().toString(),
  },
  {
    title: "Meu Número",
    subtitle: "(**) *****-1290",
    key: Math.random().toString(),
  },
  {
    title: "Meu E-mail",
    subtitle: "l*************3@g***.com",
    key: Math.random().toString(),
  },
  {
    title: "Dados pessoais",
    subtitle: "Nome, CPF e data de nascimento",
    key: Math.random().toString(),
  },
  { title: "Conta Bancária", key: Math.random().toString() },
  { title: "Taxas e limites", key: Math.random().toString() },
  { title: "Meus endereços", key: Math.random().toString() },
  { title: "Meus favoritos", key: Math.random().toString() },
  { title: "Validar identidade", key: Math.random().toString() },
  { title: "Validar identidade", key: Math.random().toString() },
  { title: "Promoções", isHeader: true, key: Math.random().toString() },
  { title: "Usar código promocional", key: Math.random().toString() },
  { title: "Convide seus amigos", key: Math.random().toString() },
  {
    title: "Minhas assinaturas",
    isHeader: true,
    key: Math.random().toString(),
  },
  { title: "Ver Minhas Assinaturas", key: Math.random().toString() },
  {
    title: "Para o meu negócio",
    isHeader: true,
    key: Math.random().toString(),
  },
  { title: "PicPay PRO", key: Math.random().toString() },
  { title: "Para estabelecimentos", key: Math.random().toString() },
  { title: "Vendas por assinaturas", key: Math.random().toString() },
  { title: "Configurações", isHeader: true, key: Math.random().toString() },
  { title: "Usar digital para pagar", key: Math.random().toString() },
  { title: "Alterar senha", key: Math.random().toString() },
  { title: "Privacidade", key: Math.random().toString() },
  { title: "Notificações", key: Math.random().toString() },
  { title: "Contas vinculadas", key: Math.random().toString() },
  { title: "Geral", isHeader: true, key: Math.random().toString() },
  { title: "Precisa de ajuda?", key: Math.random().toString() },
  { title: "Sobre o PicPay", key: Math.random().toString() },
  { title: "Desativar minha conta", key: Math.random().toString() },
];
